gateways/adyen/adyen.go, gateways/authorize_net/authorizenet.go, gateways/braintree/braintree.go, gateways/cybersource/cybersource.go, gateways/stripe/stripe.go, gateways/stripe/stripe_test.go, types.go
Update type of AVS result to match other result fields.
=> Update type of AVS result.

gateways/cybersource/cybersource.go, integration-tests/cybersource_test.go
=> [Sleet] - supporting refund

gateways/cybersource/request_builders.go, types.go
We need this information for cybersource reporting
=> Support client reference information

gateways/cybersource/request_builders.go, gateways/cybersource/types.go, integration-tests/cybersource_test.go, types.go
* Add level 3 processing for CyberSource
* Update types of Sleet level 3 data fields
=> Add level 3 processing for CyberSource.

avs.go, gateways/adyen/adyen.go, gateways/adyen/request_builder.go, gateways/adyen/translation.go, go.mod, go.sum, integration-tests/adyen_test.go, testing/auth_request.go
adyen-api-go didnt support AVS so I forked, then fixed it so now lets use it!
=> [Adyen] - Adding AVS results

contributing.md
Copied this from a generally well-accepted template I've seen a few other places
=> Contribution file

gateways/nmi/nmi.go, gateways/nmi/request_builders.go, gateways/nmi/types.go, go.mod, go.sum, integration-tests/nmi_test.go, testing/auth_request.go
[FP-209]
This PR enables sleet to send auth requests to NMI.
[FP-209]: https://boltpay.atlassian.net/browse/FP-209
=> [NMI] Authorize

gateways/nmi/nmi.go, gateways/nmi/request_builders.go, gateways/nmi/types.go, integration-tests/nmi_test.go
Part 1/3 of [FP-209]. This PR adds support and a test for NMI captures. The NMI Request type should now have everything it needs for refunds and voids as well.
[FP-209]: https://boltpay.atlassian.net/browse/FP-209
=> [NMI] Capture

gateways/nmi/nmi.go, gateways/nmi/request_builders.go, integration-tests/nmi_test.go
Part 2/3 of [FP-209].
This PR adds support and tests for NMI voids. It also modifies the NMI tests to make it harder to make some of the mistakes I've run into writing them so far.
[FP-209]: https://boltpay.atlassian.net/browse/FP-209
=> [NMI] Void

gateways/nmi/nmi.go, gateways/nmi/request_builders.go, integration-tests/nmi_test.go
Part 3/3 of [FP-209].
Adds support and tests for NMI refunds.
[FP-209]: https://boltpay.atlassian.net/browse/FP-209
=> [NMI] Refund

gateways/cybersource/cybersource.go
- Fix CyberSource API auth requests by using RFC1123Z instead of RFC1123 for the Date header.
- Add safer parsing when handling nullable response fields.
=> Use RFC1123Z for CyberSource and check AVS/CVV nullity.

types.go
@dbook13 anything else we should add? Tokenization method or anything?
=> Adding basic support for applepay

gateways/orbital/types.go
I've noticed some problems in postman if ordering is weird so fixing some issues I saw and adding some ApplePay stuff
=> Change Ordering of Fields

gateways/adyen/adyen.go, gateways/adyen/request_builder.go
Sample successful Apple Pay transaction: https://ca-test.adyen.com/ca/ca/accounts/showTx.shtml?pspReference=853600117928597D&txType=Payment
=> [adyen] apple pay support

gateways/adyen/adyen.go, gateways/adyen/request_builder.go, integration-tests/adyen_test.go
Modify Adyen request (ShopperInteraction specifically) based on if CVV is present in the sleet request which is a proxy for if the customer is new / a guest or an existing customer with a saved card.
=> [adyen] new vs. existing customer ShopperInteraction

gateways/adyen/request_builder.go
Based off of this [article](https://docs.adyen.com/payment-methods/cards/send-additional-data-for-cards/send-level-2-3-data-for-commercial-cardsl) and these [docs](https://docs.adyen.com/api-explorer/#/CheckoutService/latest/payments__reqParam_additionalData-AdditionalDataLevel23-enhancedSchemeData-customerReference).
=> [Adyen] level3 support

gateways/adyen/request_builder.go
According to Pete, when we "specify type = scheme and brand = ApplePay, we are now card network independent." This means that we should be able to process Apple Pay transactions regardless of the brand of the credit card (assuming that credit card network has been added as a payment method in the Adyen customer area).
Confirmed this with [Visa](https://ca-test.adyen.com/ca/ca/accounts/showTxPayment.shtml?setActiveAccountKey=MerchantAccount.NirajAccount&pspReference=883602031150798E&txType=Payment), [Mastercard](https://ca-test.adyen.com/ca/ca/accounts/showTx.shtml?pspReference=882602031722476J&txType=Payment), [Discover](https://ca-test.adyen.com/ca/ca/accounts/showTx.shtml?pspReference=852602035846368C&txType=Payment), and [Amex](https://ca-test.adyen.com/ca/ca/accounts/showTx.shtml?pspRe …
=> [adyen] using "applepay" as credit card brand

.circleci/config.yml
example of report https://codecov.io/github/BoltApp/sleet/commit/c0cf5e153235a60374671ac0c5a1b59a661fc0be
=> Upload coverage to codecov

gateways/adyen/request_builder.go
converts processing initiator flag to the correct Adyen flags
=> [Initiator Flags] Adyen

credit_card_network.go, integration-tests/adyen_test.go
=> [Citi-PLCC] Add citiplcc network

gateways/adyen/rtau.go, gateways/adyen/rtau_test.go, types.go
This is one of the responses that Adyen returns for rtau, and we should close the account in hail if we get this response
=> adding contact card account holder type in sleep

gateways/authorizenet/types.go, integration-tests/authorizenet_test.go
Also added a test to ensure the request works.
=> [auth net] transaction request fields need to be in the correct order

gateways/adyen/request_builder.go, gateways/adyen/request_builder_test.go
Set RecurringProcessingModel & ShopperInteraction
=> [Citi PLCC] Update for Citi PLCC

gateways/cybersource/cybersource.go, types.go
Add TransactionID to AuthorizationResponse so we can persist it in the credit card authorization table
=> Add TransactionID to AuthorizationResponse

gateways/rocketgate/rocketgate.go
Add Rocketgate gateway skeleton
=> Add Rocketgate gateway skeleton

types.go
cleaning up few comments in types.go to be more generic
=> Sleet comment cleanup

.circleci/config.yml
=> Remove code coverage from circle ci step

gateways/checkoutcom/request_builder.go
Add nil check for MerchantOrderRef for checkout.com integration.
=> Add nil check for MerchantOrderRef

gateways/authorizenet/request_builders.go, gateways/authorizenet/request_builders_test.go, gateways/authorizenet/types.go, integration-tests/authorizenet_test.go, testing/auth_request.go, types.go
Adds PhoneNumber to Sleet's auth request in Address field
Sends Email + PhoneNumber in AuthNet auth request
=> AuthNet - add phonenumber + email

gateways/authorizenet/request_builders.go, gateways/authorizenet/request_builders_test.go, testing/auth_request.go
Adds invoice number to refund request
=> authnet missing refund data

gateways/authorizenet/request_builders.go, gateways/authorizenet/request_builders_test.go
=> Revert "authnet missing refund data"

gateways/authorizenet/authorizenet.go, gateways/authorizenet/authorizenet_test.go
added the auth.net responseCode to sleet.AuthorizationResponse, also get the actual error code for "in-review" transactions
=> Add auth net responseCode to the AuthorizationResponse

gateways/adyen/adyen.go
=> Fix adyen auth panic

gateways/authorizenet/authorizenet.go, gateways/authorizenet/authorizenet_test.go, types.go
Adding metadata field to authorize response to return the authorize net authCode.
=> AuthorizeNet Add AuthCode to Response

gateways/authorizenet/request_builders.go, gateways/authorizenet/request_builders_test.go
Description: fixed an nil pointer panics in auth net request builder
TestPlan: unit tests
=> Fix auth net request nil pointer

gateways/adyen/request_builder.go, gateways/adyen/request_builder_test.go
Pass Google Pay token in Adyen Gateway Auth Request.
As documented here: https://docs.adyen.com/payment-methods/google-pay/api-only#before-you-begin.
Ticket: https://app.asana.com/0/1200616417881435/1203366263383020/f
=> WIP [Sleet] Pass Google Pay token in Adyen Auth Request

gateways/adyen/request_builder.go, gateways/adyen/request_builder_test.go, types.go
Do not construct billing address for Adyen Gpay/Apple Pay Requests
=> Do not construct billing address for Adyen Gpay Requests

gateways/adyen/adyen.go, integration-tests/adyen_test.go, types.go
Support modeled adyen errors in order to better model auths attempts that return these error types - https://docs.adyen.com/development-resources/error-codes#checkout-error-codes
=> Add auth message and result type for Adyen

gateways/nmi/nmi.go
We were not passing through the response message from NMI. Now, we are!
=> [NMI] Send Message in AuthorizationResponse

gateways/checkoutcom/checkoutcom.go
Adding optional capabilities to bind a custom http client into our CKO client.
=> [CKO] - Add tokenizer to the mix

gateways/checkoutcom/request_builder.go
We need to set the allocations into the request struct.
=> Add allocations to request object
