BoltApp/sleet

- gateways/cybersource/cybersource.go
- gateways/cybersource/request_builders.go
- gateways/cybersource/types.go
- integration-tests/cybersource_test.go
- types.go
Adds transaction reference metadata field to all requests (previously it was only in auth requests, now added to capture, refund, and void). Also incorporates this reference field in all CyberSource requests.
> Add txn ref metadata to all requests; add to Cybs.

- .circleci/config.yml
`Unit Test` is actually doing same thing as `Integration Test` step. Until the day we add unit test we can remove this step
> Remove duplicate CI steps

- gateways/firstdata/types.go
The docs dont support linking directly to the relevant models. https://docs.firstdata.com/org/gateway/docs/api#models
We're looking at
- PrimaryTransaction - https://docs.firstdata.com/org/gateway/docs/api#create-primary-transaction
- SecondaryTransaction - https://docs.firstdata.com/org/gateway/docs/api#secondary-transaction
- PaymentCardPreAuthTransaction
- PostAuthTransaction
- ReturnTransaction
- VoidTransaction
- Amount
- PaymentCardPaymentMethod
- TransactionStatus
- TransactionState
- ProcessorData
- Error
- AVSResponse
- securityCodeResponse
> Add structs for marshaling Firstdata request/response json

- gateways/adyen/request_builder.go
Add ContAuth shopper interaction to adyen credit card auth requests that will allow subsequent requests with that credit card to be authed without a cvv.
Confirmed that this change fixes the loggedIn and recharge auth flows.
> [adyen] ContAuth shopperInteraction

- gateways/adyen/request_builder.go
- integration-tests/adyen_test.go
- testing/auth_request.go
- types.go
In the Adyen auth request, differentiate between new customers who do want to save their credit card information and new customer who do not want to save their credit card information.
> [adyen] saving new customer credit card information

- gateways/nmi/nmi.go
The NMI "response" Transaction Response Variable is only 1, 2, or 3 so it doesn't provide much information about transaction declines. The "response_code" Transaction Response Variable ([values](https://secure.networkmerchants.com/gw/merchants/resources/integration/integration_portal.php#dp_appendix_3)) provides much more information about declines.
> [nmi] return response_code rather than response

- credit_card_network.go
- gateways/adyen/request_builder.go
`visa` and `mc` are the only confirmed names ([doc](https://docs.adyen.com/checkout/network-tokenization#make-a-one-off-payment-or-the-first-payment-in-a-subscription)). Will email Pete to ask about names for other cc brands.
> [adyen] use Adyen specific names for credit card brands

- gateways/adyen/request_builder.go
- types.go
I've noticed this with Stripe as well where there is some concept of the shopping carts order reference and maybe Bolt's transaction reference so lets also pass along the MerchantOrderReference and use that for Adyen
> Add MerchantOrderReference to auth request

- gateways/adyen/adyen.go
- gateways/adyen/translation.go
- gateways/cybersource/translation.go
so it's consistent with other file eg `authorizenet/transaction.go`. Also this helps increasing coverage :P because if we do switch we'd have to test all cases.
> Convert switch statements in transaction.go to map

- gateways/orbital/orbital.go
minor non-functional refactoring (that helps "increase" coverage). false is zero value for boolean so `Success: false` is just redundant, let's remove.
> Remove redundunt 'success: false' in orbital.go

- gateways/adyen/request_builder.go
When building level 3 data in the Adyen request, truncate any productcodes that are longer than 12 chars.
> [adyen] truncate product codes

- gateways/authorizenet/authorizenet.go
Because there was no Content-Type header, the bodyParser used in tk was populating `req.body` with an empty object instead of the parsed JSON. Here are two tk traces with the request body logged, the first using sleet as it is and the second using sleet after the change:
1. [Empty object](https://app.datadoghq.com/logs?cols=core_service&event=AQAAAXZoYqkUXqbslQAAAABBWFpvWXJMb0FBRGFDOHR6WHljV1VRQVU&from_ts=1607983870802&index=main&live=true&messageDisplay=inline&query=%40trace_id%3A%22DtT9QjPR0C40ndWNd7JStA%3D%3D%22&stream_sort=desc&to_ts=1608070270802)
2. [Parsed JSON](https://app.datadoghq.com/logs?cols=core_service&event=AQAAAXZoZx21FOor0AAAAABBWFpvWnpDbUFBQl9LVDVBdHowU1BnQVg&from_ts=1607983844001&index=main&live=true&messageDisplay=inline&query=%40trace_id%3A%22IM5ud2tic64l7SWsRew82w%3D …
> [authnet] Set Content-Type header in requests

- gateways/authorizenet/authorizenet_test.go
- gateways/authorizenet/request_builders.go
- gateways/authorizenet/request_builders_test.go
- testing/auth_request.go
- types.go
Per discussion [here](https://github.com/BoltApp/source/pull/10650#issuecomment-747713085), it no longer makes sense to use the refund request's `Options` field to store the last 4 digits of a credit card only for auth.net. This PR adds a new field to refund request, `Last4`, where we will now store this information.
> [authnet] Add Last4 to RefundRequest

- gateways/authorizenet/authorizenet.go
- gateways/authorizenet/authorizenet_test.go
Not returning a transaction ref for captures causes refunds to fail. Found this out while testing https://github.com/BoltApp/source/pull/10650
> [authnet] return transaction ref for capture, void, and refund

- common/pointers.go
- gateways/authorizenet/request_builders.go
- gateways/authorizenet/request_builders_test.go
- gateways/authorizenet/types.go
Adding network tokenization fields to the Auth.net CreditCard struct and adding logic to populate those fields when an Apple Pay request is sent through sleet.
[Authorize Net Docs](https://developer.authorize.net/api/reference/index.html#payment-transactions-charge-a-tokenized-credit-card)
> Authorize.net Apple Pay

- gateways/authorizenet/request_builders.go
- gateways/authorizenet/request_builders_test.go
- gateways/authorizenet/types.go
Passing the merchant order reference as the invoice number lets the merchant see their order number in their auth net dashboard.
Context: https://boltpay.slack.com/archives/C01GKB6D77F/p1622220104001800
Auth net documentation on auth request body: https://developer.authorize.net/api/reference/index.html#payment-transactions
> [auth net] send merchant-defined order reference in auth request

- gateways/nmi/nmi.go
- gateways/nmi/request_builders.go
- gateways/nmi/types.go
- integration-tests/nmi_test.go
Context: https://app.asana.com/0/1148378495214033/1200449452899513/f
> [nmi] send merchant order reference as order id

- gateways/cybersource/cybersource.go
- integration-tests/cybersource_test.go
There are two sources of errors in CyberSource API responses: Either as a top level field (as `status` and `reason`) or under `errorInformation` (as `errorInformation.Reason` and `errorInformation.Message`). This adds checks for the second case for Capture, Refund,and Void requests.
Also remove duplicate "/" from request path prefix.
Task: https://app.asana.com/0/1148378495214033/1200494589860753/f
> Add checks for errorInformation in CyberSource Capture/Refund/Void requests

- gateways/cybersource/types.go
We need to capture the transaction ID from cybersource so we can save it in the CC auth table.
> [cybs] Add transaction ID to payment auth response body

- gateways/adyen/request_builder.go
- gateways/adyen/request_builder_test.go
- gateways/cybersource/types.go
- testing/auth_request.go
- threeds.go
- types.go
Add field for 3DS verification data to `AuthorizationRequest` and update Adyen request builder to attach this data to auth requests if present.
> Add 3DS data to AuthorizationRequest and add to Adyen auths

- gateways/adyen/request_builder.go
- gateways/adyen/request_builder_test.go
- integration-tests/adyen_test.go
- integration-tests/cybersource_test.go
- testing/auth_request.go
- types.go
Adding ShippingAddress to Auth request
Refactoring BillingAddress type to reflect it being generic Address
Supporting new fields for Ayden request (ShopperIP, ShopperEmail, ShippingAddress)
> Adding shopperIP, shopperEmail, and ShippingAddress to generic Auth Request + adding support for fields in Ayden

- gateways/adyen/request_builder.go
- gateways/adyen/request_builder_test.go
Based on Cardinal's feedback the Mastercard failures may be either due to the 3DS version or the Directory Server Transaction ID. This PR updates to use the stored ID instead of the status.
#mergeWhenGreen
> Use DSTransID insteadof PAResStatus for Adyen MpiData

- gateways/cybersource/request_builders.go
- gateways/cybersource/types.go
Replace ClientReferenceInformation.Code with MerchantOrderReference (DisplayID) which used ClientTransactionReference (Bolt Order Reference) before. 
And add MerchantDefinedInformation to add ClientTransactionReference (Bolt Order Reference) there as custom merchant info.
Test:
> Replace ClientRef Code with MerchantOrderRef

- gateways/cybersource/request_builder_test.go
- gateways/cybersource/request_builders.go
- types.go
Add MerchantOrderReference to Cybersource for Capture/Void/Refund to show Display ID corresponding to Auth request.
Test:
- Capture shows correct DisplayID as Authorization
Related PR:
https://github.com/BoltApp/source/pull/24037 (with more test pictures)
> Add MerchantOrderReference to Cybersource

- gateways/adyen/request_builder.go
- gateways/adyen/request_builder_test.go
This diff builds the [adyen apple pay auth request](https://docs.adyen.com/payment-methods/apple-pay/api-only?tab=your-certificate-intro_2#make-payment). The Encrypted ApplePayToken will be passed through sleet's Options map. This is part of the effort to pass ApplePay encrypted token for Adyen (more details documented [here](https://docs.google.com/document/d/13fqmIXnwsS6Sr0pX5xyGeR1mvfR_VWYwpyt1j2UQB80/edit))
TestPlan: unit tests.
> Build Adyen ApplePay auth request

- gateways/nmi/request_builders.go
- go.mod
- go.sum
Slack thread for context: https://boltpay.slack.com/archives/C02STBR02VB/p1645036179039349
When `amountInt` has less than 2 digits i.e is less than 10, the string format logic cannot handle it. I also don't know if this amount will ever be negative, the NMI docs aren't super clear. 
Using this decimal package should fix the issue.
> Fix cases when amount is less 10 cents for NMI

- gateways/checkoutcom/checkoutcom.go
- gateways/checkoutcom/environment.go
- gateways/checkoutcom/request_builder.go
- go.mod
- go.sum
- integration-tests/checkoutcom_test.go
Added partial capture for checkout.com
- updated SDK to pick up partial capture feature
- updated usage of SDK from previous update
- added non-final classification to all checkout.com capture requests. Final voids any remaining authorized amount. Non-final leaves the remaining amount to be voided or captured later.
> Added partial capture for checkout.com

- README.md
This PR proposes that `go` syntax highlight be added to readme example.
See the rendered change here: [`README.md`](https://github.com/BoltApp/sleet/blob/31eb4b96af132a1cea1ef9a4e9c9cadf8dfeaef2/README.md)
> Add `go` syntax highlight to readme example

- gateways/checkoutcom/checkoutcom.go
Missed updating refund with the new SDK method. Not sure why integration tests missed this.
> Update refund client create

- gateways/authorizenet/authorizenet.go
Treat `responseCode = 4` as success for auth.net transactions
> Treat held in review response as success

- gateways/cybersource/request_builder_test.go
- gateways/cybersource/request_builders.go
- gateways/cybersource/types.go
- testing/auth_request.go
- types.go
We need to send 2 additional fields if we are doing multiple partial captures for Cybersource.
This is specific to first data north but that logic will live in hail.
> Allow MPC support for cybersource

- gateways/cybersource/cybersource.go
PENDING_REVIEW: refers to a transaction that has gone through the authorization process and has been flagged and placed in a review queue to be pushed forward for settlement.
Instead of reject the auth request, we will mark it as true, and later in post auth risk review job to send out notification to BigC merchants.
More context: https://app.asana.com/0/0/1202179507225216/f
> Add pending review for Cybersource

- README.md
- gateways/adyen/adyen.go
- gateways/authorizenet/authorizenet.go
- gateways/authorizenet/authorizenet_test.go
- gateways/braintree/braintree.go
- gateways/checkoutcom/checkoutcom.go
- gateways/cybersource/cybersource.go
- gateways/firstdata/firstdata.go
- gateways/firstdata/firstdata_test.go
- gateways/nmi/nmi.go
- gateways/orbital/orbital.go
- gateways/orbital/orbital_test.go
- gateways/paypalpayflow/paypalpayflow.go
- testing/auth_request.go
- types.go
- utils.go
Description: this PR adds the http status code and response headers to the `sleet.AuthorizationResponse` struct, they will be passed back to the backend service to identify PSP internal issues.
> Add http status code to AuthorizationResponse

- gateways/authorizenet/request_builders.go
- gateways/authorizenet/request_builders_test.go
- gateways/authorizenet/types.go
- integration-tests/authorizenet_test.go
Supports customerIP field in the options map for users who are using authnet fraud rules
> add customer ip to authnet options

- gateways/paypalpayflow/paypalpayflow.go
- gateways/paypalpayflow/request_builder.go
- gateways/paypalpayflow/request_builders_test.go
- gateways/paypalpayflow/types.go
- integration-tests/paypalpayflow_test.go
Description: we had an [issue](https://app.asana.com/0/1201437212753355/1202461617728612) where the currency was not correctly shown in paypal, turned out we didn't pass the currency to the request params, this PR is to fix it.
Reference: https://developer.paypal.com/api/nvp-soap/payflow/integration-guide/additional-parameters/#paypal-credit-card-transaction-request-parameters
TestPlan: unit tests + integration tests
> Add currency to paypal payflow request

- gateways/cybersource/cybersource.go
during a cybersource outage, cybersource returned an unexpected response body (see [here](https://app.datadoghq.com/logs?query=%40trace_id%3A%22Root%3D1-632bdd90-586ddc823d56633029d1457a%22&cols=service&event=AQAAAYNjWYZjO8PBkgAAAABBWU5qV1kxcUFBQkxEalgzckZ0V1R3QUo&index=main&messageDisplay=inline&stream_sort=time%2Cdesc&viz=stream&from_ts=1559954835449&to_ts=1559955735449&live=true).
This caused a nil pointer exception to be thrown
> don't throw nil pointer on empty response from cybersource during outage

- .circleci/config.yml
- gateways/adyen/adyen.go
- gateways/authorizenet/authorizenet.go
- gateways/authorizenet/authorizenet_test.go
- gateways/braintree/braintree.go
- gateways/cardconnect/cardconnect.go
- gateways/checkoutcom/checkoutcom.go
- gateways/cybersource/cybersource.go
- gateways/firstdata/firstdata.go
- gateways/firstdata/firstdata_test.go
- gateways/nmi/nmi.go
- gateways/orbital/orbital.go
- gateways/orbital/orbital_test.go
- gateways/paypalpayflow/paypalpayflow.go
- gateways/rocketgate/rocketgate.go
- gateways/stripe/request_builder.go
- gateways/stripe/stripe.go
- types.go
Creates a set of parallel methods that take a `context.Context` argument
for all payment gateways. They all follow the same pattern of passing
through `X` to `XWithContext`.
notes:
- Checkout.com & Rocketgate's SDK's do not allow a context variable to be supplied
- Adyen chose an _interesting_ way to patch `context.Context` onto their SDK
> create & fulfill ClientWithContext functions

- gateways/adyen/request_builder.go
- gateways/adyen/request_builder_test.go
- gateways/authorizenet/request_builders.go
- gateways/authorizenet/request_builders_test.go
- gateways/authorizenet/types.go
- types.go
Google Pay tokens can now be passed through the sleet request and will build a Google Pay specific request to hit the auth endpoint with
> Add Auth Net Auth Endpoint Support for Google Pay Tokens

- gateways/adyen/adyen.go
- integration-tests/adyen_test.go
Don't return an go error when response is correctly modelled.
> Fix adyen APIError failure response

- gateways/adyen/adyen.go
- integration-tests/adyen_test.go
Was previously using errors.As() to check if the returned error implements the interface. All errors implement the Adyen 'APIError' interface as there are no methods. Therefore all `ServerErrors` were getting interpreted as `APIErrors`.
> Fix modelling of Adyen server errors

- gateways/authorizenet/authorizenet.go
- gateways/authorizenet/authorizenet_test.go
- gateways/authorizenet/request_builders.go
- gateways/authorizenet/request_builders_test.go
- gateways/authorizenet/test_data/transactionDetailsErrorResponse.json
- gateways/authorizenet/test_data/transactionDetailsSuccessResponse.json
- gateways/authorizenet/types.go
- integration-tests/authorizenet_test.go
- types.go
Update Authorize Net to support Google Pay Refunds. Authorize Net requires last 4 digits of credit card number for all refunds. We don't currently store this for auth.net Google Pay transactions, however we have the ability to fetch this from auth net via api(getTransactionDetails). This PR fetches the last4 from getTransactionDetails and populates the CC number in the refund request
Related bug: https://app.asana.com/0/1200616417881435/1204243318709223/f
Thread: https://boltpay.slack.com/archives/C03U3T92Y8Z/p1680433093558869
> Update Authorize Net to support Google Pay Refunds

- gateways/cybersource/cybersource.go
- types.go
Add `processorInformation.approvalCode` and `processorInformation.responseCode` to cybersource auth response.
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1204920789048078
> Add additional metadata to cybersource auth response

- gateways/paypalpayflow/paypalpayflow.go
- gateways/paypalpayflow/request_builder.go
- gateways/paypalpayflow/request_builders_test.go
- gateways/paypalpayflow/types.go
Use the COMMENT1 field for merchant order reference in paypal payflow auth request.
> Add merchant order reference to Paypal Payflow auth request

- gateways/cybersource/cybersource.go
- gateways/cybersource/request_builder_test.go
- gateways/cybersource/request_builders.go
- gateways/cybersource/translation.go
- gateways/cybersource/types.go
- integration-tests/cybersource_test.go
- types.go
This PR upgrade the CyberSource client to support tokenization using the CyberSource Token Management Service (TMS).
Client consumers can request to tokenize the information in an authorization request by setting the CyberSourceTokenization option with a list of token types they want to create. They can then retrieve the resulting tokens from the CreatedTokens field in the authorization response.
The external API was designed to be processor-agnostic, without using CyberSource-specific terms. While only the token types relevant to CyberSource were defined, they are designed to be generic and reusable for other processors and new token types.
I added two new unit tests to verify that the presence of the tokenization option in the request results in the addition of tokenization fields in …
> Support Cybersource Tokenization

- gateways/cybersource/cybersource.go
- gateways/cybersource/types.go
- integration-tests/cybersource_test.go
- testing/utils.go
The documentation I followed [here](https://developer.cybersource.com/docs/cybs/en-us/tms/developer/all/rest/tms-developer/Authorizations-for-Tokens/Authorize-a-Payment-and-Create-Customer-Tokens.html) used an incorrect schema. The real responses observed do not match the documentation.
This PR updates the fields we use to match the real observed responses.
> Fix response fields used by CyberSource tokenization

- .circleci/config.yml
The integration test environment is currently not maintained. Remove the build step to run them so that commits won't be blocked by these tests.
> Disable automatic integration tests

- gateways/authorizenet/request_builders.go
- gateways/authorizenet/request_builders_test.go
- gateways/authorizenet/types.go
Our L2/L3 Line Item inputs were not fully compliant with Authorize.net's specification.
Firstly, we were sending the incorrect item fields. CommodityCode was used for the item ID when instead ProductCode should be used. And ProductCode was used for the name when Description should be used.
Next, Authorize.net requires an item ID and a name on every item. Some cart items may not have a product code or description added. To facilitate successful auths when limited data is available, we will use the item index as a substitute for item ID, and the item ID as substitute for the item name. There is precedent for adding this logic for other L2/L3-supported processors.
Lastly, I renamed some types and fields and added notes regarding the specific requirements for each field from Authorize.net's …
> [Authorize.net] Various corrections to L2/L3 data inputs

- integration-tests/cybersource_test.go
Enable a previously skipped test. The test was skipped because our account did not have the feature. We do now, so we can run the test.
> Enable integration test for CyberSource tokenization

- gateways/checkoutcom/request_builder.go
- types.go
- Adding AmountSplits to Auth, Capture and Refund structs. Immediate use case is for Capture, but good to add to other structs for future use case
- Populate AmountAllocations using the AmountSplits field in CKO capture request
https://api-reference.checkout.com/#operation/captureAPayment
> [CKO] Add AmountSplits types and populate AmountAllocations for CKO Capture request
